version: "3.5"

services:

  alice:
    build: .
    # Note: Instead of using `dhxdocker/datahighway:latest` from Docker Hub, which
    # may reflects the latest version on Github, during development we want to build
    # a Docker container using the Dockerfile, which contains the latest local changes of our current branch.
    # Run docker-compose -f docker-compose-dev.yml build --no-cache to build and create a new image.
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30333:30333 # TCP
      - 9944:9944 # WS
      - 9933:9933 # RPC
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-alice.sh

  bob:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30334:30333
      - 9945:9944
      - 9934:9933
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-bob.sh

  charlie:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30335:30333
      - 9946:9944
      - 9935:9933
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-charlie.sh

  dave:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30336:30333
      - 9947:9944
      - 9936:9933
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-dave.sh

  eve:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30337:30333
      - 9948:9944
      - 9937:9933
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-eve.sh

volumes:
  basePath:
