version: "3"

services:
  node-1:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-1.sh
  node-2:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30337:30333
      - 9948:9944
      - 9937:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-2.sh
  node-3:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30338:30333
      - 9949:9944
      - 9938:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-3.sh
  node-4:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30339:30333
      - 9950:9944
      - 9939:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-4.sh
  node-5:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30340:30333
      - 9951:9944
      - 9940:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-5.sh
