name: CI

on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust stable
        run: |
          rustup toolchain update --no-self-update stable
          rustup default stable
          rustup component add clippy rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all --all-features --

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        cargo_flags:
          - ""
          - "--all-features"
        include:
          # Integration tests are disabled on Windows as they take *way* too
          # long to pull the Docker image
          - os: windows-latest
            test_flags: --skip buildtest --skip integration
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust
        run: |
          rustup toolchain update --no-self-update stable
          rustup default stable
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly


      - name: Build rustwide
        run: 
          cargo update
          cargo build --all ${{ matrix.cargo_flags }}

      - name: Test rustwide
        run: 
          cargo update
          cargo test --all ${{ matrix.cargo_flags }} -- ${{ matrix.test_flags }}
